language: go
go:
  - 1.7
  - 1.8
  - master
sudo: required
services:
  - docker
before_install:
  - docker run -d -p 10101:10101 pilosa/pilosa:v0.3.2
  - go get github.com/mattn/goveralls      
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
script:
  - glide up && $HOME/gopath/bin/goveralls -service=travis-ci -flags="-tags=integration"
