language: go
go:
  - 1.8
  - 1.9
  - master
sudo: required
group: deprecated-2017Q2
before_install:
  - curl -o pilosa https://storage.googleapis.com/pilosa/pilosa-sumreduce && chmod +x pilosa && ./pilosa server
  - go get github.com/mattn/goveralls
  - go get -u github.com/golang/dep/cmd/dep
addons:
script:
  - dep ensure && $HOME/gopath/bin/goveralls -service=travis-ci -ignore "internal/public.pb.go" -flags="-tags=integration"
